"""Semantic MCU host protocol and codecs."""

from redsun_aht.mcu.commands import (
    MAX_PATTERN_CHUNK_BYTES,
    BeginPattern,
    Capabilities,
    CommandError,
    ErrorCode,
    PatternChunk,
    PatternEncoding,
    SequenceDefinition,
    SequenceStep,
    pattern_checksum,
)
from redsun_aht.mcu.human import (
    HUMAN_MCU_COMMAND_HELP,
    AllOffCommand,
    ArmSequenceCommand,
    DefineSequenceCommand,
    GetCapabilitiesCommand,
    HumanMcuCommand,
    HumanMcuCommandError,
    ShowPatternCommand,
    StartSequenceCommand,
    StopCommand,
    UploadPatternCommand,
    parse_human_mcu_command,
)
from redsun_aht.mcu.protocol import (
    MAX_PAYLOAD_BYTES,
    PROTOCOL_VERSION,
    ChecksumMismatchError,
    MessageType,
    Packet,
    PacketFlag,
    ProtocolDecodeError,
    cobs_decode,
    cobs_encode,
    crc16_ccitt,
    decode_packet,
    encode_packet,
)
from redsun_aht.mcu.simulator import SimulatedMcu, SimulatedMcuTransport

__all__ = [
    "HUMAN_MCU_COMMAND_HELP",
    "MAX_PATTERN_CHUNK_BYTES",
    "MAX_PAYLOAD_BYTES",
    "PROTOCOL_VERSION",
    "AllOffCommand",
    "ArmSequenceCommand",
    "BeginPattern",
    "Capabilities",
    "ChecksumMismatchError",
    "CommandError",
    "DefineSequenceCommand",
    "ErrorCode",
    "GetCapabilitiesCommand",
    "HumanMcuCommand",
    "HumanMcuCommandError",
    "MessageType",
    "Packet",
    "PacketFlag",
    "PatternChunk",
    "PatternEncoding",
    "ProtocolDecodeError",
    "SequenceDefinition",
    "SequenceStep",
    "ShowPatternCommand",
    "SimulatedMcu",
    "SimulatedMcuTransport",
    "StartSequenceCommand",
    "StopCommand",
    "UploadPatternCommand",
    "cobs_decode",
    "cobs_encode",
    "crc16_ccitt",
    "decode_packet",
    "encode_packet",
    "parse_human_mcu_command",
    "pattern_checksum",
]
